import 'dart:io';

void main() async {
  final jsFile = File('bin/parsers/js_ast.js');
  if (!jsFile.existsSync()) {
    print('❌ Error: bin/parsers/js_ast.js not found');
    exit(1);
  }
  final jsContent = await jsFile.readAsString();
  final dartContent =
      '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by tool/generate_assets.dart
// Edit bin/parsers/js_ast.js instead.

const String jsParserScript = r\'\'\'
$jsContent
\'\'\';
''';

  final outputFile = File('lib/parsers/generated_js_script.dart');
  await outputFile.writeAsString(dartContent);

  print('✅ Successfully generated lib/parsers/generated_js_script.dart');
}
